# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
  [main.params]
    icon = "fa-solid fa-pen"

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-user"
