baseURL = "https://tarzalt.dev"
languageCode = "en-us"
title = "Tarzalt Lyes - Portfolio"
theme = "FixIt"

[params]
description = "Welcome to my professional portfolio site. Explore my projects, read my blog posts, and learn more about my work."
keywords = ["portfolio", "blog", "projects", "Tarzalt Lyes"]
[params.analytics]
enable = false
[params.analytics.google]
      id = "G-DSSGSXVXJE"
      anonymizeIP = true
[params.analytics.fathom]
id = ""
server = ""


[params.header]
desktopMode = "sticky" # Header remains at the top of the page as you scroll
mobileMode = "auto"    # Automatically adjust header based on device type
[params.header.title]
logo = "https://avatars.githubusercontent.com/u/24894134?s=400&u=f2b942884829f239c8283549050b67e04e659232&v=4"
name = "Tarzalt Lyes - Portfolio"

[params.footer]
enable = false
copyright = false
author = false
[params.footer.siteTime]
enable = true                  # Displays the site creation time if you prefer
icon = "fa-solid fa-heartbeat" # Icon next to the site time

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

# Home page configuration
[params.home]
paginate = 10
[params.home.profile]
enable = true
avatarURL = "https://avatars.githubusercontent.com/u/24894134?s=400&u=f2b942884829f239c8283549050b67e04e659232&v=4"
title = "Welcome to my portfolio!"
subtitle = "I am Tarzalt Lyes, a dedicated software engineer and technology enthusiast. Here you can find my latest projects and blog posts about my journey in tech."
typeit = false
social = true

[params.home.posts]
enable = true
paginate = 6

# Social Links Configuration
[params.social]
GitHub = "lyestarzalt"
LinkedIn = "lyes-tarzalt"
